package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallLeader;
import org.linlinjava.litemall.db.domain.LitemallLeaderExample;

public interface LitemallLeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    long countByExample(LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int insert(LitemallLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int insertSelective(LitemallLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeader selectOneByExample(LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeader selectOneByExampleSelective(@Param("example") LitemallLeaderExample example, @Param("selective") LitemallLeader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallLeader> selectByExampleSelective(@Param("example") LitemallLeaderExample example, @Param("selective") LitemallLeader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    List<LitemallLeader> selectByExample(LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeader selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallLeader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    LitemallLeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeader selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallLeader record, @Param("example") LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallLeader record, @Param("example") LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}