package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRouteLeader;
import org.linlinjava.litemall.db.domain.LitemallRouteLeaderExample;

public interface LitemallRouteLeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    long countByExample(LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int insert(LitemallRouteLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRouteLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRouteLeader selectOneByExample(LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRouteLeader selectOneByExampleSelective(@Param("example") LitemallRouteLeaderExample example, @Param("selective") LitemallRouteLeader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallRouteLeader> selectByExampleSelective(@Param("example") LitemallRouteLeaderExample example, @Param("selective") LitemallRouteLeader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    List<LitemallRouteLeader> selectByExample(LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRouteLeader selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRouteLeader.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    LitemallRouteLeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRouteLeader selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRouteLeader record, @Param("example") LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRouteLeader record, @Param("example") LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRouteLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRouteLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallRouteLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_route_leader
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}