package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallLeaderUser;
import org.linlinjava.litemall.db.domain.LitemallLeaderUserExample;

public interface LitemallLeaderUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int insert(LitemallLeaderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallLeaderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeaderUser selectOneByExample(LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeaderUser selectOneByExampleSelective(@Param("example") LitemallLeaderUserExample example, @Param("selective") LitemallLeaderUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallLeaderUser> selectByExampleSelective(@Param("example") LitemallLeaderUserExample example, @Param("selective") LitemallLeaderUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    List<LitemallLeaderUser> selectByExample(LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeaderUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallLeaderUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    LitemallLeaderUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallLeaderUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallLeaderUser record, @Param("example") LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallLeaderUser record, @Param("example") LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallLeaderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallLeaderUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallLeaderUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_leader_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}